version: "3.8"

services:
  video-storage-server:
    container_name: video-storage-server
    build:
      context: .
      dockerfile: ./docker/8.2/Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.2/video-storage-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ".:/var/www/html"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
    networks:
      - sail
    depends_on:
      - minio

  minio:
    container_name: minio
    image: "minio/minio:latest"
    ports:
      - "${FORWARD_MINIO_PORT:-9000}:9000"
      - "${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900"
    environment:
      MINIO_ROOT_USER: sail
      MINIO_ROOT_PASSWORD: password
    volumes:
      - "sail-minio:/data/minio"
    networks:
      - sail
    command: 'minio server /data/minio --console-address ":8900"'
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - "http://localhost:9000/minio/health/live"
      retries: 3
      timeout: 5s

  createbuckets:
    container_name: createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 sail password;
      /usr/bin/mc rm -r --force myminio/local;
      /usr/bin/mc mb myminio/local;
      /usr/bin/mc policy download myminio/local;
      exit 0;
      "
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-minio:
    driver: local
